const fmt=n=>new Intl.NumberFormat('en-US').format(n);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bars=(items,labelKey,valueKey)=>{if(!items?.length)return '<p class="micro">No data available.</p>';const max=Math.max(...items.map(x=>Number(x[valueKey])||0),1);return items.map(x=>`<div class="bar-row"><span>${esc(x[labelKey])}</span><div class="bar-track"><div class="bar-fill" style="width:${100*(Number(x[valueKey])||0)/max}%"></div></div><span class="bar-value">${fmt(x[valueKey])}</span></div>`).join('')};
fetch('data/journal-data.json').then(r=>{if(!r.ok)throw new Error(`Data request failed: ${r.status}`);return r.json()}).then(d=>{
 document.getElementById('updated').textContent=`Data updated ${d.meta.dataUpdated} · Coverage: ${d.meta.coverage}`;document.getElementById('footerDate').textContent=`Dashboard updated ${d.meta.dataUpdated}`;
 const cards=[['Publication years',d.summary.publicationYears],['Issues published',d.summary.issuesPublished],['Articles published',d.summary.articlesPublished],['Contributing authors',d.summary.contributingAuthors],['Countries represented',d.summary.countriesRepresented],['Article views',d.summary.articleViews],['PDF file requests',d.summary.pdfDownloads],['International collaborations',d.summary.internationalCollaborationArticles]];
 document.getElementById('summary').innerHTML=cards.map(([l,v])=>`<article class="card"><span class="value">${fmt(v)}</span><span class="label">${esc(l)}</span></article>`).join('');
 document.getElementById('yearChart').innerHTML=bars(d.publicationByYear,'year','articles');document.getElementById('typeChart').innerHTML=bars(d.articleTypes,'label','count');document.getElementById('countryChart').innerHTML=bars(d.countries,'country','authors');
 document.getElementById('collabRate').textContent=`${d.summary.internationalCollaborationRate}%`;document.getElementById('collabText').textContent=`${d.summary.internationalCollaborationArticles} of ${d.summary.articlesPublished} published articles include authors affiliated with more than one country.`;
 const t=d.monthlyEngagement,max=Math.max(...t.views,...t.downloads,1);document.getElementById('timeline').innerHTML=t.labels.map((m,i)=>`<div class="month-group" title="${esc(m)}: ${fmt(t.views[i])} views; ${fmt(t.downloads[i])} PDF file requests"><div class="col views" style="height:${Math.max(1,100*t.views[i]/max)}%"></div><div class="col downloads" style="height:${Math.max(1,100*t.downloads[i]/max)}%"></div><span class="month-label">${esc(m)}</span></div>`).join('');
 const usageList=items=>items.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a><span class="meta">${esc(x.issue)} · ${fmt(x.views)} views · ${fmt(x.downloads)} PDF file requests</span></li>`).join('');document.getElementById('topViewed').innerHTML=usageList(d.topViewed);document.getElementById('topDownloaded').innerHTML=usageList(d.topDownloaded);
 const w=d.wos,wCards=[['WoS citation links',w.citationLinks],['Unique citing documents',w.uniqueCitingDocuments],['Cited JSOMER articles',w.citedJsomerArticles],['Citing source journals',w.citingSourceJournals],['Countries and regions',w.countriesRegions]];document.getElementById('wosCards').innerHTML=wCards.map(([l,v])=>`<div class="metric-card"><strong>${fmt(v)}</strong><span>${esc(l)}</span></div>`).join('');
 document.getElementById('wosYearChart').innerHTML=bars(w.citingDocumentsByYear,'year','documents');document.getElementById('wosAreaChart').innerHTML=bars(w.researchAreas,'area','documents');document.getElementById('wosSourceChart').innerHTML=bars(w.topCitingSources,'source','documents');
 document.getElementById('wosTopArticles').innerHTML=w.mostCitedArticles.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a><span class="meta">${x.year} · ${fmt(x.citations)} WoS citation${x.citations===1?'':'s'}</span></li>`).join('');document.getElementById('wosIndexes').innerHTML=w.indexes.map(x=>`<span class="index-badge">${esc(x.index)} · ${fmt(x.documents)}</span>`).join('');document.getElementById('wosNote').textContent=w.methodNote;
 const p=d.peerReview,pCards=[['Manuscripts entering peer review',p.manuscriptsEnteringPeerReview],['Reviewers invited',p.reviewersInvited],['Completed review reports',p.completedReports],['Median invitation-to-completion time',`${p.medianInvitationToCompletionDays} days`]];document.getElementById('peerCards').innerHTML=pCards.map(([l,v])=>`<div class="metric-card"><strong>${typeof v==='number'?fmt(v):esc(v)}</strong><span>${esc(l)}</span></div>`).join('');
 const pmax=Math.max(...p.annualActivity.flatMap(x=>[x.invitations,x.completed]),1);document.getElementById('peerYearChart').innerHTML=p.annualActivity.map(x=>`<div class="pair-row"><strong>${x.year}</strong><div class="pair-chart"><div class="pair-track" title="${x.invitations} invitations"><div class="pair-fill invitations" style="width:${100*x.invitations/pmax}%"></div></div><div class="pair-track" title="${x.completed} completed reports"><div class="pair-fill completed" style="width:${100*x.completed/pmax}%"></div></div></div><span class="pair-value">${x.invitations} / ${x.completed}</span></div>`).join('');document.getElementById('within21').textContent=`${p.completedWithin21DaysPct}%`;document.getElementById('byDeadline').textContent=`${p.completedByDeadlinePct}%`;
 document.getElementById('modelGrid').innerHTML=d.publishingModel.map(x=>`<div class="model-item">${esc(x)}</div>`).join('');
}).catch(e=>{document.body.insertAdjacentHTML('beforeend','<p style="padding:20px;color:#b00020">Dashboard data could not be loaded.</p>');console.error(e)});